### ISSUE TITLE
Update to v1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/tableschema-rb#16]
# Description

V1 of the Table Schema spec is in release candidate stage. The [Python](https://github.com/frictionlessdata/tableschema-py) and [Javascript](https://github.com/frictionlessdata/tableschema-js) libraries have been updated. While there are still a couple of things unresolved, this library can be updated to support V1 of the specs now.

# Tasks

- [x] Review the whole family of [specifications](http://specs.frictionlessdata.io)
- [x] Review the [implementation notes](http://specs.frictionlessdata.io/implementation/)
- [x] Review either the Python ([Data Package](https://github.com/frictionlessdata/datapackage-py) [Table Schema](https://github.com/frictionlessdata/tableschema-py)) or JavaScript ([Data Package](https://github.com/frictionlessdata/datapackage-js) [Table Schema](https://github.com/frictionlessdata/tableschema-js)) reference implementations (whichever language you feel most comfortable reading)
- [x] Review the [stack reference](https://github.com/frictionlessdata/stack#frictionless-data-stack)
- [x] Review the blog post that announces [v1 of the specifications](https://hackmd.io/KwUzE5wIwRgWgGYENzDgFmAgzHKA2fJOABmHwGMATEmK8GIoA===)
- [x] Review the test packages that can be used to [test your work](https://github.com/frictionlessdata/testsuite-py/tree/master/datasets) (in addition to the normal and expected unit tests)
- [x] Review the [OKFN Coding Standards](https://github.com/okfn/coding-standards)
  - Parts of the coding standard are language specific, and parts are workflow specific. The workflow points are important for you. If you want to contribute language-related standards to our docs for your language, we welcome it!
- [x] Write a set of high-level issues for each library, on the respective issue tracker, that outline the work plan. Do this with some feedback from @roll who has done V1 updates for the Python and Javascript libraries
  - Note the structure of this issue: A narrative description and a specific list of tasks. Follow a similar pattern
  -  The sequence of work is important: start with the Table Schema library first, as the Data Package library has a direct dependency on it

**Comment by roll** [comment]
@georgiana-b 
So here is some intro based on my experience. 

### Package name

Gem `jsontableschema`-> `tableschema`

### Type support

I think the best approach will be some reverse-engineering:
- port all this tests https://github.com/frictionlessdata/tableschema-py/tree/master/tests/types (changing it to use `Field` e.g. `Field({'type': 'any}).cast_value`)
- run and see discrepancies 
- add missing types
- update other types

This test suite is not complete yet but it's really good source of how Field should cast values. 

### Missing values

Next big thing is a specs simplification related to null values. Now you could do 3 independent steps:
- get if this a missing/null value
- cast value
- check constraints

There is a new `missingValues` property. So see py/js libs how it's implemented.

### Updated jsonschema

Across libraries I use simple approach to sync with specs - https://github.com/frictionlessdata/tableschema-py/blob/master/Makefile#L16-L17. So you could:
- add something like this (also you could add test to check jsonschema is not out-of-date)
- then update jsonschema
- and fix all stuff which is not compatible with Table Schema v1

**Comment by georgiana-b** [comment]
I opened the high-level issues for bringing this gem in line with [Table Schema v1-spec](http://specs.frictionlessdata.io/table-schema/) and labeled them `Version-1`.
